#!/bin/sh
# Submit assembly and run job with
# abend output enabled.

cat src/MANASM \
    src/MANONE \
    src/CLMAG \
    src/MANDEL \
    src/CRDINIT \
    src/CRDTRAN \
    src/DMO \
    src/DMAND \
    src/PRTMAND \
    src/MANASE \
    > job

echo "/*" >> job
echo -n "//" >> job
nc -w1 localhost 3505 < job
